In [ ]:
import pandas as pd
room_l=[10,11,12,18,17,15]
room_b=[15,17,18,20,22,21]
df=pd.DataFrame({'r_l':room_l,'r_b':room_b})
print(df)

In [ ]:
df['area']=df['r_l']*df["r_b"]
print(df)

In [ ]:
import numpy as np
df['area']=np.where(df['area']>=300,"big",np.where(df['area']<=170,"small","medium"))
df
df1=pd.get_dummies(data=df)
print(df1)

In [ ]:
age=[18,20,23,19,18,22]
city=["A","B","A","B","C","A"]
df2=pd.DataFrame({"age":age,"city":city})
print(df)
df3=pd.get_dummies(data=df)
print(df3)

In [ ]:
df3=pd.get_dummies(data=df,drop_first=True)
print(df3)

In [ ]:
import matplotlib.pyplot as plt
import seaborn as sns

import pandas as pd
room_l=[10,11,12,18,17,15]
room_b=[15,17,18,20,22,21]
df=pd.DataFrame({'r_l':room_l,'r_b':room_b})
print(df)
sns.regplot(data=df,x="r_l",y="r_b")

In [ ]:
df=pd.read_csv("Book1.csv")
print(df.head())

In [ ]:
sns.regplot(x="cgpa",y="package",data=df)
plt.show()

In [ ]:
x=df.iloc[:,0:1]
y=df.iloc[:,-1]
print(type(x))
print(type(y))

In [ ]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=5)
print(x_train.shape)
print(y_train.shape)
print(x_test.shape)
print(y_test.shape)

In [ ]:
from sklearn.linear_model import LinearRegression
lr=LinearRegression()
lr.fit(x_train,y_train)
y_pred=lr.predict(x_test)
print("Actual",y_test,"Predicted",y_pred)
print(lr.coef_)
print(lr.intercept_)

In [ ]:
from sklearn import metrics
print("MAE:",metrics.mean_absolute_error(y_test,y_pred))
print("MAE:",metrics.mean_squared_error(y_test,y_pred))
print("R2 Score:",metrics.r2_score(y_test,y_pred))

In [ ]:
y_pred=lr.predict([[9.85]])
print(y_pred)

In [ ]:
df=pd.read_csv("CAR DETAILS FROM CAR DEKHO.csv")
sns.regplot(x="km_driven",y="selling_price",data=df)
plt.show()

In [ ]:
from sklearn.model_selection import train_test_split
x=df[["km_driven"]]
y=df["selling_price"]
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=5)

In [ ]:
from sklearn.linear_model import LinearRegression
lr=LinearRegression()
lr.fit(x_train,y_train)
y_pred=lr.predict(x_test)
print("Actual",y_test,"Predicted",y_pred)
print(lr.coef_)
print(lr.intercept_)

In [ ]:
y_pred=lr.predict([[35000]])
print(y_pred)

In [ ]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
df=pd.read_csv("olympic100.csv")
sns.regplot(x="year",y="time",data=df)

In [ ]:
from sklearn.model_selection import train_test_split
x=df[['year']]
y=df['time']
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.1,random_state=5)

In [ ]:
from sklearn.linear_model import LinearRegression
lr=LinearRegression()
lr.fit(x_train,y_train)
y_pred=lr.predict(x_test)
print("Actual",y_test,"Predicted",y_pred)
print(lr.coef_)
print(lr.intercept_)

In [ ]:
y_pred1=lr.predict([[2024]])
print(y_pred1)

In [ ]:
from sklearn import metrics
print("MSE: ",metrics.mean_squared_error(y_test,y_pred))
print("MAE: ",metrics.mean_absolute_error(y_test,y_pred))
print("R2_score: ",metrics.r2_score(y_test,y_pred))

In [ ]:
df1=pd.read_csv("CAR DETAILS FROM CAR DEKHO.csv")
df1.head()
df1["Age"]=2024-df1["year"]

In [ ]:
x=df1[["Age","km_driven","fuel","seller_type","transmission"]]
y=df1["selling_price"]
x=pd.get_dummies(x)
print(x)

In [ ]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=5)

In [ ]:
from sklearn.linear_model import LinearRegression
lr=LinearRegression()
lr.fit(x_train,y_train)
y_pred=lr.predict(x_test)
print("Actual",y_test,"Predicted",y_pred)
print(lr.coef_)
print(lr.intercept_)

In [ ]:
from sklearn import metrics
print("MSE: ",metrics.mean_squared_error(y_test,y_pred))
print("MAE: ",metrics.mean_absolute_error(y_test,y_pred))
print("R2_score: ",metrics.r2_score(y_test,y_pred))

In [ ]:
df2=pd.read_csv("winequalityN.csv")
# clean the data set and after that check multipal
df2.isna().sum()

In [ ]:
data=df2.dropna()

In [ ]:
x=data[["type","fixed acidity","volatile acidity","citric acid","residual sugar","chlorides","free sulfur dioxide","total sulfur dioxide","density","pH","sulphates","alcohol"]]
y=data["quality"]
x=pd.get_dummies(x)
print(x)

In [ ]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=5)

In [ ]:
from sklearn.linear_model import LinearRegression
lr=LinearRegression()
lr.fit(x_train,y_train)
y_pred=lr.predict(x_test)
print("Actual",y_test,"Predicted",y_pred)
print(lr.coef_)
print(lr.intercept_)

In [ ]:
from sklearn import metrics
print("MSE: ",metrics.mean_squared_error(y_test,y_pred))
print("MAE: ",metrics.mean_absolute_error(y_test,y_pred))
print("R2_score: ",metrics.r2_score(y_test,y_pred))

In [ ]:
# ------------------------Polynomial Reg.--------------------------------#

In [ ]:
df=pd.read_csv("data_poly.csv")
print(df)

In [ ]:
x=df.iloc[:,1:2]
y=df.iloc[:,2]

In [ ]:
from sklearn.linear_model import LinearRegression

In [ ]:
from sklearn.preprocessing import PolynomialFeatures

In [ ]:
poly=PolynomialFeatures(degree=3)
model_poly=poly.fit_transform(x)
lr=LinearRegression()
lr.fit(model_poly,y)
plt.scatter(x,y)
plt.plot(x,lr.predict(model_poly))
plt.show()
y_pred=lr.predict(model_poly)
print(y_pred)

In [ ]:
y_train=lr.predict(poly.fit_transform([[80]]))
print(metrics.r2_score(y,y_pred))

In [ ]:
df=pd.read_csv("olympic100.csv")

In [ ]:
from sklearn.model_selection import train_test_split
x=df[['year']]
y=df['time']
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.1,random_state=5)

In [ ]:
from sklearn.linear_model import LinearRegression
from sklearn.preprocessing import PolynomialFeatures
poly=PolynomialFeatures(degree=3)
model_poly=poly.fit_transform(x_train)
lr=LinearRegression()
lr.fit(model_poly,y_train)

plt.scatter(x_train,y_train)
plt.plot(x_train,lr.predict(model_poly))
plt.show()

In [ ]:
lr.predict(poly.fit_transform([[2036]]))

In [1]:
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
df=pd.read_csv("diabetes.csv")
print(df)

     Pregnancies  Glucose  BloodPressure  SkinThickness  Insulin   BMI  \
0              6      148             72             35        0  33.6   
1              1       85             66             29        0  26.6   
2              8      183             64              0        0  23.3   
3              1       89             66             23       94  28.1   
4              0      137             40             35      168  43.1   
..           ...      ...            ...            ...      ...   ...   
763           10      101             76             48      180  32.9   
764            2      122             70             27        0  36.8   
765            5      121             72             23      112  26.2   
766            1      126             60              0        0  30.1   
767            1       93             70             31        0  30.4   

     DiabetesPedigreeFunction  Age  Outcome  
0                       0.627   50        1  
1                  

In [2]:
x=df.drop("Outcome",axis=1)
y=df["Outcome"]
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=5)

In [3]:
from sklearn.neighbors import KNeighborsClassifier
knn=KNeighborsClassifier(n_neighbors=27)
knn.fit(x_train,y_train)
prediction=knn.predict(x_test)
print(y_test,'/n',prediction)

567    0
123    0
615    0
492    0
288    0
      ..
432    0
480    1
7      0
564    0
40     0
Name: Outcome, Length: 154, dtype: int64 /n [0 1 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 1 0 0 0 1 0 1 0 0 0 0 0 1 0 0 0 0 0 0 0
 0 0 0 0 1 0 1 0 1 1 0 0 0 1 0 0 0 0 0 0 0 1 0 1 1 1 0 0 0 0 0 1 0 1 0 0 1
 1 1 0 1 1 0 0 1 1 1 0 0 0 0 0 0 1 0 0 1 0 1 1 0 0 0 0 0 1 1 0 0 0 0 1 0 0
 1 0 0 0 0 0 1 0 0 1 1 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 1 0 0 1 0 0 0 0 0 0
 1 0 0 0 0 0]


In [7]:
from sklearn.metrics import confusion_matrix

In [8]:
cm=confusion_matrix(y_test,prediction)
print(cm)

[[86 14]
 [28 26]]


In [12]:
TN=cm[0][0]
FP=cm[0][1]
FN=cm[1][0]
TP=cm[1][1]
print(TN,FP,FN,TP)

86 14 28 26


In [13]:
accuracy=(TP+TN)/(TP+FP+FN+TN)
accuracy

0.7272727272727273

In [14]:
print("Error rate= ",1-accuracy)

Error rate=  0.2727272727272727


In [15]:
sensitivity=TP/(TP+FN)
sensitivity

0.48148148148148145

In [16]:
specificity=TN/(TN+FP)
specificity

0.86

In [17]:
x.columns

Index(['Pregnancies', 'Glucose', 'BloodPressure', 'SkinThickness', 'Insulin',
       'BMI', 'DiabetesPedigreeFunction', 'Age'],
      dtype='object')

In [18]:
df1=pd.read_csv("Iris.csv")
print(df)

     Pregnancies  Glucose  BloodPressure  SkinThickness  Insulin   BMI  \
0              6      148             72             35        0  33.6   
1              1       85             66             29        0  26.6   
2              8      183             64              0        0  23.3   
3              1       89             66             23       94  28.1   
4              0      137             40             35      168  43.1   
..           ...      ...            ...            ...      ...   ...   
763           10      101             76             48      180  32.9   
764            2      122             70             27        0  36.8   
765            5      121             72             23      112  26.2   
766            1      126             60              0        0  30.1   
767            1       93             70             31        0  30.4   

     DiabetesPedigreeFunction  Age  Outcome  
0                       0.627   50        1  
1                  

In [26]:
x=df1.drop('Species',axis=1)
y=df1["Species"]
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,random_state=5,test_size=0.2)

In [27]:
from sklearn.neighbors import KNeighborsClassifier
knn=KNeighborsClassifier(n_neighbors=27)
knn.fit(x_train,y_train)
prediction=knn.predict(x_test)
print(y_test,'/n',prediction)

82     Iris-versicolor
134     Iris-virginica
114     Iris-virginica
42         Iris-setosa
109     Iris-virginica
57     Iris-versicolor
1          Iris-setosa
70     Iris-versicolor
25         Iris-setosa
84     Iris-versicolor
66     Iris-versicolor
133     Iris-virginica
102     Iris-virginica
107     Iris-virginica
26         Iris-setosa
23         Iris-setosa
123     Iris-virginica
130     Iris-virginica
21         Iris-setosa
12         Iris-setosa
71     Iris-versicolor
128     Iris-virginica
48         Iris-setosa
72     Iris-versicolor
88     Iris-versicolor
148     Iris-virginica
74     Iris-versicolor
96     Iris-versicolor
63     Iris-versicolor
132     Iris-virginica
Name: Species, dtype: object /n ['Iris-versicolor' 'Iris-virginica' 'Iris-virginica' 'Iris-setosa'
 'Iris-virginica' 'Iris-versicolor' 'Iris-setosa' 'Iris-versicolor'
 'Iris-setosa' 'Iris-versicolor' 'Iris-versicolor' 'Iris-virginica'
 'Iris-virginica' 'Iris-virginica' 'Iris-setosa' 'Iris-setosa'
 'Iris-virgi

In [31]:
from sklearn.metrics import confusion_matrix

In [32]:
cm=confusion_matrix(y_test,prediction)
print(cm)

[[ 8  0  0]
 [ 0 11  0]
 [ 0  0 11]]


In [56]:
# Write a python program to train knn classifier using the following steps:-
# 1) Split the data set into training and testing data set testing size=0.3 random state=42 initilizing the neghibor classifier 5
# and print the accuracy score of classifier. Data set name is wineQuality
df2=pd.read_csv("winequalityN.csv")
# clean the data set and after that check multipal
df2.isna().sum()

type                     0
fixed acidity           10
volatile acidity         8
citric acid              3
residual sugar           2
chlorides                2
free sulfur dioxide      0
total sulfur dioxide     0
density                  0
pH                       9
sulphates                4
alcohol                  0
quality                  0
dtype: int64

In [57]:
data=df2.dropna()

In [58]:
x=data[["type","fixed acidity","volatile acidity","citric acid","residual sugar","chlorides","free sulfur dioxide","total sulfur dioxide","density","pH","sulphates","alcohol"]]
y=data["quality"]
x=pd.get_dummies(x)
print(x)

      fixed acidity  volatile acidity  citric acid  residual sugar  chlorides  \
0               7.0             0.270         0.36            20.7      0.045   
1               6.3             0.300         0.34             1.6      0.049   
2               8.1             0.280         0.40             6.9      0.050   
3               7.2             0.230         0.32             8.5      0.058   
4               7.2             0.230         0.32             8.5      0.058   
...             ...               ...          ...             ...        ...   
6491            6.8             0.620         0.08             1.9      0.068   
6492            6.2             0.600         0.08             2.0      0.090   
6494            6.3             0.510         0.13             2.3      0.076   
6495            5.9             0.645         0.12             2.0      0.075   
6496            6.0             0.310         0.47             3.6      0.067   

      free sulfur dioxide  

In [59]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.3,random_state=42)

In [60]:
from sklearn.neighbors import KNeighborsClassifier
knn=KNeighborsClassifier(n_neighbors=5)
knn.fit(x_train,y_train)
prediction=knn.predict(x_test)
print(y_test,'/n',prediction)

1143    5
2708    6
4943    4
4194    6
5956    7
       ..
1383    6
1254    5
5847    7
3075    7
5716    5
Name: quality, Length: 1939, dtype: int64 /n [5 5 5 ... 5 6 6]


In [61]:
from sklearn.metrics import confusion_matrix

In [62]:
cm=confusion_matrix(y_test,prediction)
print(cm)

[[  0   0   4   2   1   0   0]
 [  2   4  35  19   3   0   0]
 [  2  13 350 242  45   0   0]
 [  0   7 262 471  84   4   0]
 [  0   7  59 163  94   4   0]
 [  0   0  13  32  12   4   0]
 [  0   0   0   1   0   0   0]]


In [63]:
from sklearn.metrics import accuracy_score
accuracy=accuracy_score(y_test,prediction)
print(accuracy)

0.47601856627127387


In [64]:
from sklearn.datasets import load_wine
wine=load_wine()
x=wine.data
y=wine.target
print(x)
print(y)

[[1.423e+01 1.710e+00 2.430e+00 ... 1.040e+00 3.920e+00 1.065e+03]
 [1.320e+01 1.780e+00 2.140e+00 ... 1.050e+00 3.400e+00 1.050e+03]
 [1.316e+01 2.360e+00 2.670e+00 ... 1.030e+00 3.170e+00 1.185e+03]
 ...
 [1.327e+01 4.280e+00 2.260e+00 ... 5.900e-01 1.560e+00 8.350e+02]
 [1.317e+01 2.590e+00 2.370e+00 ... 6.000e-01 1.620e+00 8.400e+02]
 [1.413e+01 4.100e+00 2.740e+00 ... 6.100e-01 1.600e+00 5.600e+02]]
[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2
 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2]
